// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class AddressGroup extends pulumi.CustomResource {
    /**
     * Get an existing AddressGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): AddressGroup {
        return new AddressGroup(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'xyz:resources:AddressGroup';

    /**
     * Returns true if the given object is an instance of AddressGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AddressGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AddressGroup.__pulumiType;
    }

    public /*out*/ readonly addressGroupId!: pulumi.Output<number>;
    public readonly domains!: pulumi.Output<string[]>;
    public readonly prefixes!: pulumi.Output<string[]>;

    /**
     * Create a AddressGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AddressGroupArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.domains === undefined) && !opts.urn) {
                throw new Error("Missing required property 'domains'");
            }
            if ((!args || args.prefixes === undefined) && !opts.urn) {
                throw new Error("Missing required property 'prefixes'");
            }
            resourceInputs["domains"] = args ? args.domains : undefined;
            resourceInputs["prefixes"] = args ? args.prefixes : undefined;
            resourceInputs["addressGroupId"] = undefined /*out*/;
        } else {
            resourceInputs["addressGroupId"] = undefined /*out*/;
            resourceInputs["domains"] = undefined /*out*/;
            resourceInputs["prefixes"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AddressGroup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a AddressGroup resource.
 */
export interface AddressGroupArgs {
    domains: pulumi.Input<pulumi.Input<string>[]>;
    prefixes: pulumi.Input<pulumi.Input<string>[]>;
}
