// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Veco.Resources.Outputs
{

    [OutputType]
    public sealed class ServiceGroupTcp
    {
        public readonly int PortEnd;
        public readonly int PortStart;

        [OutputConstructor]
        private ServiceGroupTcp(
            int portEnd,

            int portStart)
        {
            PortEnd = portEnd;
            PortStart = portStart;
        }
    }
}
