// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Xyz.Resources.Outputs
{

    [OutputType]
    public sealed class ServiceGroupIcmp
    {
        public readonly int CodeHigh;
        public readonly int CodeLow;
        public readonly int IcmpType;

        [OutputConstructor]
        private ServiceGroupIcmp(
            int codeHigh,

            int codeLow,

            int icmpType)
        {
            CodeHigh = codeHigh;
            CodeLow = codeLow;
            IcmpType = icmpType;
        }
    }
}
