// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace resources {
    export interface ServiceGroupIcmpArgs {
        codeHigh: pulumi.Input<number>;
        codeLow: pulumi.Input<number>;
        icmpType: pulumi.Input<number>;
    }

    export interface ServiceGroupTcpArgs {
        portEnd: pulumi.Input<number>;
        portStart: pulumi.Input<number>;
    }

    export interface ServiceGroupUdpArgs {
        portEnd: pulumi.Input<number>;
        portStart: pulumi.Input<number>;
    }
}
